### PR TITLE
Cover case when the default profile is chosen and it has `profile_options`

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Without this, we can have forms with no default profile set in the form.
Screenshot 2023-07-12 at 16 22 44

We do make the first profile the default one in the back end, but that's too far down the workflow and that makes the new `_validate_posted_profile_options` function to fail because the `selected_options` contains info about the profile, for example `{'profile': None}` instead of the options corresponding to the default profile.

~This could have been also fixed by moving the default just before the check https://github.com/batpad/kubespawner/blob/68a71f939e73325469b5e664a43b9b0b440b7b69/kubespawner/spawner.py#L3196-L3197~

~But since all the other options have defaults set by the form (it's not clear to me from the HTML why, but removing all defaults, still show defaults in the form :/ ), why not have the profiles also have the same.~

cc @yuvipanda

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
Wait, this breaks having a default profile when the API is used instead of the form :(. Investigating...

**Comment by GeorgianaElena** [comment]
I think the only change needed here is the on in the html form

**Comment by yuvipanda** [comment]
@GeorgianaElena I'm somewhat confused too, particularly around usage when this just gets used via API. Should the code changes here outside of the form be reverted?

I agree all this points to the code needing to be simplified.

**Comment by GeorgianaElena** [comment]
Closing this in favor of https://github.com/batpad/kubespawner/pull/2

**Pull request closed without merging**
